### ISSUE TITLE
there is already a spark.dataframe to tfrecord connector in tf/ecosystem though.

### ISSUE THREAD

**Issue by yupbank** [linkedin/Avro2TF#41]
https://github.com/tensorflow/ecosystem/tree/master/spark/spark-tensorflow-connector

since you already use spark to do transformation. what's the benefit of convert Avro2TF instead of a format free connector? 

and there is actually a avro dataset reader exists here https://github.com/tensorflow/io/blob/master/tensorflow_io/avro/20190307-avro-dataset.md

**Comment by zhangxuhong** [comment]
Hi Peng,

Thanks for reaching out. Avro2TF is not just changing format of your data. One key function of Avro2TF is to collect the vocab list or index map. For example, for a text feature, most of the time, we need to collect the vocab and them convert text to a list of ids. Internal in Avro2TF, we are also using TensorFlow spark connector to dump TFRecords. For the TensorFlow avro dataset API, it's also from LinkedIn. Internally, we use it load avro format training data (output of Avro2TF).
